// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Username  string
	Password  string
	Name      string
	Phone     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
