version: "3.7"

services:
  postgres:
    image: postgres:17-alpine
    container_name: my_project_postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_project
      PGDATA: /data/postgres
    volumes:
      - my_project_postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - my_project_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_project_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: amir1103.tr@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - my_project_pgadmin:/var/lib/pgadmin
    ports:
      - "8070:80"
    networks:
      - my_project_network
    restart: unless-stopped
    depends_on:
      - postgres
  
  redis:
    image: redis:7.4-alpine
    container_name: my_project_redis_container
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - my_project_redis:/data
    ports:
      - "6379:6379"
    networks:
      - my_project_network
    restart: unless-stopped

volumes:
  my_project_postgres:
  my_project_pgadmin:
  my_project_redis:

networks:
  my_project_network:
    driver: bridge
